app:
  port: :8000

db:
  host: localhost
  port: 5432
  user: user
  password: 123456
  db_name: blog

redis:
  host: localhost
  port: 6379
  password: 123456
  db: 0

account:
  phone: 15583251761
  password: 123456

feishu:
  app_id: ""
  app_secret: ""

jwt:
  secret_key: secret_key_t1an
